src/components/mainpage/BoxOfiice.jsx, src/components/mainpage/MainTabIn/BestReview.jsx, src/components/mainpage/MainTabIn/NewPosts.jsx, src/components/mainpage/MainTabList.jsx, src/components/signup/SignupBox.jsx, src/pages/SignUp.js, src/shared/api.js
회원가입 폼 디자인 수정
회원가입 중복확인시 형식 확인 추가
메인페이지 박스오피스 데이터 안뜨는 에러 수정
메인페이지 박스오피스, 베스트한줄평, 최신리뷰 json server 연결 확인
=> Feat/mainpage 박스오피스 안뜨는 에러 수정

src/apis/postApi.js, src/pages/Community/CommunityDetail.js
=> feat:community 수정, 좋아요 등록/삭제 구현

src/pages/Community/CommunityDetail.js
=> style:버튼 수정

src/pages/Community/CommunityDetail.js
=> style: 좋아요 버튼 수정

src/pages/Community/CommunityDetail.js
=> feat:예외 추가

src/components/common/Footer.jsx, src/components/common/navbar/NavBar.jsx
- 네비게이션 패딩 조정
- 푸터 반응형 레이아웃 조정
=> fix: 네비게이션, 푸터 레이아웃 조정

src/components/mainpage/BoxOfiice.jsx, src/components/mainpage/MainTabIn/BestReview.jsx, src/components/mainpage/MainTabIn/NewPosts.jsx
=> fix : 뱃지 수정, 메인페이지로 이동시 스크롤 맨위로

src/components/community/LikesButton.jsx, src/pages/Community/CommunityDetail.js
=> fix: 좋아요 오류 수정

src/apis/postApi.js, src/components/community/LikeButton.jsx, src/pages/Community/CommunityDetail.js
=> refactor:코드 정리

src/components/mainpage/MainTabIn/BestReview.jsx
좋아요 수 부분이 화면 끝에서 잘려서
좋아요 수를 밑으로 내려서 해결
=> style : 베스트리뷰 모바일 화면시 짤림 수정

src/components/challenge/ChallengeHeader.jsx, src/components/favorite/FavoriteCard.jsx, src/pages/Mypage/MyFavorites.js
=> style: 챌린지 페이지 버튼 UI 수정

src/components/community/BoardContainer.jsx, src/components/community/ReviewItem.jsx, src/components/mypage/PostItem.jsx, src/pages/Mypage/MyOneLineReviews.js, src/pages/Mypage/MyPosts.js
- 커뮤니티 중간 경로 detail 제거
- 최소 높이 추가
=> fix: 커뮤니티 경로 수정

src/components/common/Footer.jsx, src/components/common/Layout.jsx, src/components/myBadges/MainBadge.jsx, src/components/mypage/OneLineReviewItem.jsx
- 대표 배지 호버 이펙트 추가
- 푸터 및 레이아웃 디자인 변경
=> style: 한줄평 순서 수정

src/components/mainpage/MainTabIn/NewPosts.jsx, src/index.js, src/pages/Community/CommunityDetail.js
=> feat: 상세페이지 뒤로 가기 추가

src/components/mainpage/BoxOffice.jsx
=> style : 박스오피스 캐로셀 반응형 수정

src/apis/postApi.js, src/components/community/ReviewItem.jsx, src/components/mypage/challenge/BadgeItem.jsx, src/components/mypage/info/NicknameChange.jsx
=> feat: 게시글 댓글 수 좋아요 수 표시

package.json, src/components/common/notification/NoticeSoket.jsx, src/components/common/notification/Notification.jsx, src/components/detail/Oneline.jsx, src/pages/Main.js, yarn.lock
=> fix : 알림 서버연결 테스트

src/apis/postApi.js, src/components/community/Comment.jsx, src/components/community/CommentItemHeader.jsx, src/components/community/Comments.jsx, src/components/community/SubComment.jsx, src/components/community/SubCommentForm.jsx, src/components/community/SubCommentList.jsx
=> feat: 대댓글 기능 구현

src/components/common/Header.jsx, src/components/common/navbar/LoginBox.jsx, src/components/common/navbar/MobileNavbar.jsx, src/components/common/navbar/MyLinks.jsx, src/components/common/navbar/NavMainMenu.jsx, src/components/community/CommentForm.jsx, src/components/community/CommentItemFooter.jsx, src/components/community/Comments.jsx, src/components/community/CommunityFooter.jsx, src/components/community/SearchBox.jsx, src/components/community/SubComment.jsx, src/components/community/SubCommentForm.jsx, src/components/mypage/oneLineReview/MyOneLineReviewList.jsx, src/pages/Community/CommunityDetail.js, src/pages/Mypage/MyOneLineReviews.js
=> fix: 모바일 메뉴 링크 오류 수정

src/components/challenge/ChallengeList.jsx, src/components/common/LogoBox.jsx, src/components/community/CommentItemHeader.jsx, src/components/mypage/challenge/MainBadge.jsx
=> style: 댓글 UI 수정
